name: Build Package
on: [push, release]

jobs:
  Build-Release-Package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: sudo ./install-dev-requirements.sh
      - run: ./package.sh
      - run: |
          if [ ${{ github.event_name }} = "release" ]; then
            RELEASE_VERSION_NAME="${GITHUB_REF/refs\/tags\//}"
            hub release edit -m "" -a *.deb "${RELEASE_VERSION_NAME}"
          fi
